### ISSUE TITLE
Feature request - PHP8 support

### ISSUE THREAD

**Issue by estevao** [Stichoza/laravel-coderunner#3]
+-----------+
~ $ composer global require stichoza/laravel-coderunner
Changed current directory to /Users/estevao/.composer

  [InvalidArgumentException]
  Package stichoza/laravel-coderunner has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - stichoza/laravel-coderunner v1.0.8 requires php ^7.2 which does not match your installed version 8.1.3.
+-----------+

Any chance of adding PHP8 support? I was playing around but wasn't able to make it work so far. Thanks.

**Comment by ejunker** [comment]
Until it is updated to support PHP 8, you could try this:
```
composer global require --ignore-platform-reqs stichoza/laravel-coderunner
```

**Comment by Stichoza** [comment]
I've just added `^8.0` support, sorry for the delay
